Repository tmax-cloud/hypersds-operator, pull requests merged in 2021-04, with the labels that each got.

#11 Update spec of CephCluster CR
  api/v1alpha1/cephcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/hypersds.tmax.io_cephclusters.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
Labels: size/XL

#1 Implement controller of CephCluster CR and fix e2e
  .github/workflows/main.yml
  Makefile
  config/rbac/role.yaml
  config/samples/hypersds_v1alpha1_cephcluster.yaml
  controllers/access_configmap.go
  controllers/access_configmap_test.go
  controllers/cephcluster_controller.go
  controllers/install_configmap.go
  controllers/install_configmap_test.go
  controllers/provision_pod.go
  controllers/provision_pod_test.go
  controllers/role.go
  controllers/role_test.go
  controllers/rolebinding.go
  controllers/rolebinding_test.go
  controllers/secret.go
  controllers/secret_test.go
  controllers/test_util.go
  go.mod
  hack/e2e.sh
  main.go
Labels: size/XXL

#12 Prepare project merge with hypersds-provisioner
  .github/workflows/assign.yml
  .github/workflows/main.yml
  Makefile
Labels: ci/cd, size/S
