Repository tmax-cloud/hypersds-operator, pull requests merged in 2021-03, with the labels that each got.

#7 Add User Guide & Design docs
  docs/USERGUIDE.md
  docs/assets/overall.png
  docs/assets/workflow.png
  docs/design/hypersds-operator.md
Labels: documentation, size/L

#9 Add guide for csi deployment
  deploy/csi/cephfs/csi-cephfsplugin-provisioner.yaml
  deploy/csi/cephfs/csi-cephfsplugin.yaml
  deploy/csi/cephfs/csi-nodeplugin-rbac.yaml
  deploy/csi/cephfs/csi-provisioner-rbac.yaml
  deploy/csi/cephfs/pod.yaml
  deploy/csi/cephfs/pvc.yaml
  deploy/csi/cephfs/secret.yaml
  deploy/csi/cephfs/storageclass.yaml
  deploy/csi/csi-config-map.yaml
  deploy/csi/namespace.yaml
  deploy/csi/rbd/csi-nodeplugin-rbac.yaml
  deploy/csi/rbd/csi-provisioner-rbac.yaml
  deploy/csi/rbd/csi-rbdplugin-provisioner.yaml
  deploy/csi/rbd/csi-rbdplugin.yaml
  deploy/csi/rbd/pod.yaml
  deploy/csi/rbd/pvc.yaml
  deploy/csi/rbd/secret.yaml
  deploy/csi/rbd/storageclass.yaml
  deploy/csi/tool.sh
  docs/USERGUIDE.md
Labels: documentation, size/XXL

#6 Add prolinux cluster script to manage e2e test vms
  .github/workflows/main.yml
  Makefile
  config/samples/hypersds_v1alpha1_cephcluster.yaml
  hack/boilerplate.go.txt
  hack/cluster.sh
Labels: ci/cd, size/L
